### ISSUE TITLE
NetworkError

### ISSUE THREAD

**Issue by dscroft** [LiaScript/LiaScript-Exporter#46]
Starting in the last few days any attempt to use the exporter produces a NetworkError (full error below). This is occurring on multiple local machines and is also in the a GitHub workflow (configured as described here https://github.com/LiaScript/LiaScript-Exporter/issues/45)

```
NetworkError
    at XMLHttpRequest.send (/usr/local/lib/node_modules/@liascript/exporter/node_modules/xhr2/lib/xhr2.js:281:19)
    at Object.b (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:11280)
    at /usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:8491
    at Hr (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:8629)
    at Mr (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:8183)
    at /usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:9709
    at Qr (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:9745)
    at /usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:9258
    at Object.send (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:102937)
    at ru (/usr/local/lib/node_modules/@liascript/exporter/dist/index.js:2:199268)
```

**Comment by dscroft** [comment]
My mistake, in re-structuring the project I had moved the top level markdown file and failed to change the --input parameter to be relative to the newly set --path parameter.

**Comment by dscroft** [comment]
Issue occurs when I have an import: statement in markdown file pointing at a local file. Issue disappears if I change the import to a url.

**Example dir structure**
demo_project/
- demo.md
- macros.md

**Running the command from the root of the project:**
liaex --path demo_project --input demo_project/demo.md --format scorm1.2 --output demo

If demo.md contains the following I get NetworkError
```
<!--
import: macros.md
-->
```

If demo.md contains the following it works, I would prefer to keep everything in the scorm package. I can see if I open the scorm that the macros.md file is being included in the .zip file.
```
<!--
import: https://raw.githubusercontent.com/dscroft/lia/main/demo_project/macros.md
-->
```

**Comment by andre-dietrich** [comment]
Thanks for reporting ... If you update the exporter, this problem should be fixed ... hopefully ;-)
